USE [master]
GO
/****** Object:  Database [ezblogin]    Script Date: 2020/11/23 8:13:03 ******/
CREATE DATABASE [ezblogin]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ezblogin', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ezblogin.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ezblogin_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ezblogin_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ezblogin] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ezblogin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ezblogin] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ezblogin] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ezblogin] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ezblogin] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ezblogin] SET ARITHABORT OFF 
GO
ALTER DATABASE [ezblogin] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ezblogin] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ezblogin] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ezblogin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ezblogin] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ezblogin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ezblogin] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ezblogin] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ezblogin] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ezblogin] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ezblogin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ezblogin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ezblogin] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ezblogin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ezblogin] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ezblogin] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ezblogin] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ezblogin] SET RECOVERY FULL 
GO
ALTER DATABASE [ezblogin] SET  MULTI_USER 
GO
ALTER DATABASE [ezblogin] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ezblogin] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ezblogin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ezblogin] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ezblogin] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'ezblogin', N'ON'
GO
ALTER DATABASE [ezblogin] SET QUERY_STORE = OFF
GO
USE [ezblogin]
GO
/****** Object:  Table [dbo].[System_User]    Script Date: 2020/11/23 8:13:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[System_User](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [varchar](200) NULL,
	[Password] [varchar](200) NULL,
	[UserType] [varchar](200) NULL,
 CONSTRAINT [PK__System_U__3214EC277CC24E9C] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAS_ClassesRecord]    Script Date: 2020/11/23 8:13:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAS_ClassesRecord](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CourseID] [int] NULL,
	[Hours] [float] NULL,
	[ClasseTitle] [varchar](200) NULL,
	[UId] [varchar](200) NULL,
	[Position] [varchar](200) NULL,
 CONSTRAINT [PK__TAS_Clas__3214EC27DCA265C0] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAS_CourseRecord]    Script Date: 2020/11/23 8:13:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAS_CourseRecord](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CourseCode] [varchar](200) NULL,
	[CourseTitle] [varchar](200) NULL,
	[Dept] [varchar](200) NULL,
	[Schooltime] [datetime] NULL,
	[HQ] [int] NULL,
	[UNITA] [int] NULL,
	[UNITB] [int] NULL,
	[UNITC] [int] NULL,
	[ITGY] [int] NULL,
	[MSAF] [int] NULL,
	[SMG] [int] NULL,
 CONSTRAINT [PK__TAS_Cour__3214EC2731D1AE76] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAS_Duty]    Script Date: 2020/11/23 8:13:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAS_Duty](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[StaffNo] [varchar](200) NULL,
	[CostCentre] [varchar](200) NULL,
	[Hours] [float] NULL,
	[Duty] [varchar](200) NULL,
 CONSTRAINT [PK__TAS_Duty__3214EC2771D24C92] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAS_Staff]    Script Date: 2020/11/23 8:13:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAS_Staff](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[No] [varchar](200) NULL,
	[CostCentre] [varchar](200) NULL,
	[Dept] [varchar](200) NULL,
	[Role] [varchar](200) NULL,
 CONSTRAINT [PK__TAS_Staf__3214EC2717C266A3] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAS_User]    Script Date: 2020/11/23 8:13:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAS_User](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UId] [nvarchar](50) NULL,
	[Fname] [varchar](200) NULL,
	[Lname] [varchar](200) NULL,
	[Title] [varchar](200) NULL,
	[StaffNo] [varchar](200) NULL,
	[Type] [varchar](200) NULL,
 CONSTRAINT [PK__TAS_User__3214EC276065AB00] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [ezblogin] SET  READ_WRITE 
GO
